name: "CI Pipeline for build and test"

on:
    push:
        branches:
            - main

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Install node js"
              uses: actions/setup-node@v4
              with:
                node-version: '24.x'

            - name: "Code checkout"
              uses: actions/checkout@v4

            - name: "Build code and test"
              run: |
                    npm run build
                    npm run test  

            - name: "Start application"
              run: npm run start

            - name: "Upload artifact"
              uses: actions/upload-artifact@v4
              with:
                    name: build
                    path: dist
