name: "CI Pipeline for build and test"

on:
    push:
        branches:
            - main

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:

            - name: "Code checkout"
              uses: actions/checkout@v4

            - name: "Upload artifact"
              uses: actions/upload-artifact@v4
              with:
                    name: build
                    path: dist
