name: "Scheduled Pipeline"

on:
    schedule:
      - cron: "*/2 * * * *"
    workflow_dispatch: 
    push:
        branches:
            - main

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Setup node"
              uses: actions/setup-node@v4
              with:
                node-version: "24.*"

            - name: "Code checkout"
              uses: actions/checkout@v4
            
            - name: "install dependencies"
              run: npm install

            - name: "Run test"
              run: npm run test

            - name: "Bild the app"
              run: npm run build
              
